//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlXnaApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlXnaApp1.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        public static string AddDialog {
            get {
                return ResourceManager.GetString("AddDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string AddFriendButton {
            get {
                return ResourceManager.GetString("AddFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding chat page....
        /// </summary>
        public static string AddingChatPage {
            get {
                return ResourceManager.GetString("AddingChatPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add person.
        /// </summary>
        public static string AddPerson {
            get {
                return ResourceManager.GetString("AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently application is loading some items from Vkontakte. Please, wait a bit and repeat action..
        /// </summary>
        public static string AppIsLoadingItems {
            get {
                return ResourceManager.GetString("AppIsLoadingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application notifications.
        /// </summary>
        public static string ApplicationNotifications {
            get {
                return ResourceManager.GetString("ApplicationNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachmentLabel {
            get {
                return ResourceManager.GetString("AttachmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachments.
        /// </summary>
        public static string AttachmentsLabel {
            get {
                return ResourceManager.GetString("AttachmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string AudioContentLabel {
            get {
                return ResourceManager.GetString("AudioContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number, login or e-mail.
        /// </summary>
        public static string AuthLoginLabel {
            get {
                return ResourceManager.GetString("AuthLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        public static string CallPhone {
            get {
                return ResourceManager.GetString("CallPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save this change..
        /// </summary>
        public static string CanNotSaveThisChange {
            get {
                return ResourceManager.GetString("CanNotSaveThisChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no enough access rights to add this user..
        /// </summary>
        public static string CantAddThisUser {
            get {
                return ResourceManager.GetString("CantAddThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such chat cannot be created..
        /// </summary>
        public static string CantCreateChat {
            get {
                return ResourceManager.GetString("CantCreateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no enough access rights to remove this user..
        /// </summary>
        public static string CantRemoveThisUser {
            get {
                return ResourceManager.GetString("CantRemoveThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type symbols from the picture.
        /// </summary>
        public static string CaptchaLabel {
            get {
                return ResourceManager.GetString("CaptchaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change chat.
        /// </summary>
        public static string ChangeChatLabel {
            get {
                return ResourceManager.GetString("ChangeChatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        public static string ChangePhotoButton {
            get {
                return ResourceManager.GetString("ChangePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose existing photo.
        /// </summary>
        public static string ChoosePhotoButton {
            get {
                return ResourceManager.GetString("ChoosePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string ContactsGroup {
            get {
                return ResourceManager.GetString("ContactsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts synchronization....
        /// </summary>
        public static string ContactsSyncing {
            get {
                return ResourceManager.GetString("ContactsSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string ContactsTab {
            get {
                return ResourceManager.GetString("ContactsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create chat.
        /// </summary>
        public static string CreateChat {
            get {
                return ResourceManager.GetString("CreateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create chat you need to select name and friends to talk with..
        /// </summary>
        public static string CreateChatError {
            get {
                return ResourceManager.GetString("CreateChatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decline request.
        /// </summary>
        public static string DeclineRequestButton {
            get {
                return ResourceManager.GetString("DeclineRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete friend.
        /// </summary>
        public static string DeleteFriendButton {
            get {
                return ResourceManager.GetString("DeleteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For fast, free and convenient messaging with friends and contacts.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialogs.
        /// </summary>
        public static string DialogsTab {
            get {
                return ResourceManager.GetString("DialogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable notification sound for the next {0}.
        /// </summary>
        public static string DisableNotificationFormatMessage {
            get {
                return ResourceManager.GetString("DisableNotificationFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable sounds for the next hour.
        /// </summary>
        public static string DisableSoundOneHour {
            get {
                return ResourceManager.GetString("DisableSoundOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable sounds for the next 8 hours.
        /// </summary>
        public static string DisableSoundSeveralHours {
            get {
                return ResourceManager.GetString("DisableSoundSeveralHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string DocumentContentLabel {
            get {
                return ResourceManager.GetString("DocumentContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error. Please make sure that you&apos;ve entered the correct phone or email and password and try again..
        /// </summary>
        public static string ErrorAuthorization {
            get {
                return ResourceManager.GetString("ErrorAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading.
        /// </summary>
        public static string ErrorUploading {
            get {
                return ResourceManager.GetString("ErrorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward.
        /// </summary>
        public static string ForwardButton {
            get {
                return ResourceManager.GetString("ForwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarded message.
        /// </summary>
        public static string ForwardedContentLabel {
            get {
                return ResourceManager.GetString("ForwardedContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your messages was marked to forward and will be send immediately when you press Send button in any chat or dialog..
        /// </summary>
        public static string ForwardMessagesDescription {
            get {
                return ResourceManager.GetString("ForwardMessagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend request.
        /// </summary>
        public static string FriendRequest {
            get {
                return ResourceManager.GetString("FriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend requests ({0}).
        /// </summary>
        public static string FriendRequests {
            get {
                return ResourceManager.GetString("FriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string FriendsGroup {
            get {
                return ResourceManager.GetString("FriendsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friends.
        /// </summary>
        public static string FriendsTab {
            get {
                return ResourceManager.GetString("FriendsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.googleapis.com/maps/api/staticmap?center={0},{1}&amp;zoom=11&amp;size=320x240&amp;sensor=false.
        /// </summary>
        public static string GeolocationMapUriFormatMessage {
            get {
                return ResourceManager.GetString("GeolocationMapUriFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for location....
        /// </summary>
        public static string GettingLocation {
            get {
                return ResourceManager.GetString("GettingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for your friends and contacts among all registred users..
        /// </summary>
        public static string GlobalSearchDescription {
            get {
                return ResourceManager.GetString("GlobalSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable your location service by going to Settings -&gt; Location -&gt; Turn on Location Services option..
        /// </summary>
        public static string GPSNotEnabled {
            get {
                return ResourceManager.GetString("GPSNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-app notifications.
        /// </summary>
        public static string InAppNotificationsLabel {
            get {
                return ResourceManager.GetString("InAppNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string IncomeMessage {
            get {
                return ResourceManager.GetString("IncomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal api error occured. Please get the latest available version of this application..
        /// </summary>
        public static string InternalApiError {
            get {
                return ResourceManager.GetString("InternalApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invite friend.
        /// </summary>
        public static string InviteFriend {
            get {
                return ResourceManager.GetString("InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is typing....
        /// </summary>
        public static string IsTypingLabel {
            get {
                return ResourceManager.GetString("IsTypingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave chat.
        /// </summary>
        public static string LeaveChat {
            get {
                return ResourceManager.GetString("LeaveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading messages...
        /// </summary>
        public static string LoadingMessagesLabel {
            get {
                return ResourceManager.GetString("LoadingMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull to load more.
        /// </summary>
        public static string LoadMoreLabel {
            get {
                return ResourceManager.GetString("LoadMoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location was saved and will be immediately send when you press Send button in this view..
        /// </summary>
        public static string LocationAttachmentDescription {
            get {
                return ResourceManager.GetString("LocationAttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string LocContentLabel {
            get {
                return ResourceManager.GetString("LocContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not sent..
        /// </summary>
        public static string MessageNotSentLabel {
            get {
                return ResourceManager.GetString("MessageNotSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        public static string MessagesTab {
            get {
                return ResourceManager.GetString("MessagesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name.
        /// </summary>
        public static string NameChatLabel {
            get {
                return ResourceManager.GetString("NameChatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account.
        /// </summary>
        public static string NewAccountLabel {
            get {
                return ResourceManager.GetString("NewAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages yet.
        /// </summary>
        public static string NoMessagesLabel {
            get {
                return ResourceManager.GetString("NoMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of attachments.
        /// </summary>
        public static string NumberAttachments {
            get {
                return ResourceManager.GetString("NumberAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        public static string NumberMemebersFormatMessage {
            get {
                return ResourceManager.GetString("NumberMemebersFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages.
        /// </summary>
        public static string NumberMessagesInChat {
            get {
                return ResourceManager.GetString("NumberMessagesInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineLabel {
            get {
                return ResourceManager.GetString("OnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other users.
        /// </summary>
        public static string OtherUsersGroup {
            get {
                return ResourceManager.GetString("OtherUsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not read yet.
        /// </summary>
        public static string OutMessageNotRead {
            get {
                return ResourceManager.GetString("OutMessageNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people you may know.
        /// </summary>
        public static string PeopleMayKnowLabel {
            get {
                return ResourceManager.GetString("PeopleMayKnowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is incorrect or already in use..
        /// </summary>
        public static string PhoneInUse {
            get {
                return ResourceManager.GetString("PhoneInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string PhotoContentLabel {
            get {
                return ResourceManager.GetString("PhotoContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to possible friends.
        /// </summary>
        public static string PossibleFriendsGroup {
            get {
                return ResourceManager.GetString("PossibleFriendsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press back to close.
        /// </summary>
        public static string PressBackLabel {
            get {
                return ResourceManager.GetString("PressBackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to push notifications.
        /// </summary>
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove attachment.
        /// </summary>
        public static string RemoveAttachmentButton {
            get {
                return ResourceManager.GetString("RemoveAttachmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove dialog.
        /// </summary>
        public static string RemoveDialog {
            get {
                return ResourceManager.GetString("RemoveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string RemovePerson {
            get {
                return ResourceManager.GetString("RemovePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request SMS again.
        /// </summary>
        public static string RequestSMS {
            get {
                return ResourceManager.GetString("RequestSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string ResendButton {
            get {
                return ResourceManager.GetString("ResendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes....
        /// </summary>
        public static string SavingChanges {
            get {
                return ResourceManager.GetString("SavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search among your friends and contacts..
        /// </summary>
        public static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search friend requests....
        /// </summary>
        public static string SearchFriendRequests {
            get {
                return ResourceManager.GetString("SearchFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string SelectUserCaption {
            get {
                return ResourceManager.GetString("SelectUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message....
        /// </summary>
        public static string SendingMessage {
            get {
                return ResourceManager.GetString("SendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send invitation.
        /// </summary>
        public static string SendInvitationButton {
            get {
                return ResourceManager.GetString("SendInvitationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send a message.
        /// </summary>
        public static string SendMessageButton {
            get {
                return ResourceManager.GetString("SendMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string SentMessage {
            get {
                return ResourceManager.GetString("SentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share location.
        /// </summary>
        public static string ShareLocationButton {
            get {
                return ResourceManager.GetString("ShareLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up.
        /// </summary>
        public static string SignupButton {
            get {
                return ResourceManager.GetString("SignupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t sign up user. One of parameters is incorrect or such user already exists..
        /// </summary>
        public static string SignUpFailed {
            get {
                return ResourceManager.GetString("SignUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type code from SMS message.
        /// </summary>
        public static string SmsCodeLabel {
            get {
                return ResourceManager.GetString("SmsCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound notifications disabled until {0}.
        /// </summary>
        public static string SoundNotificationsDisabledUntilFormatMessage {
            get {
                return ResourceManager.GetString("SoundNotificationsDisabledUntilFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync contacts.
        /// </summary>
        public static string SyncContactsButton {
            get {
                return ResourceManager.GetString("SyncContactsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync your phone contacts with your VK friends list.
        /// </summary>
        public static string SyncDescription {
            get {
                return ResourceManager.GetString("SyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        public static string TakePhotoButton {
            get {
                return ResourceManager.GetString("TakePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast.
        /// </summary>
        public static string Toast {
            get {
                return ResourceManager.GetString("Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day(s).
        /// </summary>
        public static string TotalDays {
            get {
                return ResourceManager.GetString("TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour(s).
        /// </summary>
        public static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute(s).
        /// </summary>
        public static string TotalMinutes {
            get {
                return ResourceManager.GetString("TotalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgainLabel {
            get {
                return ResourceManager.GetString("TryAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        public static string TwoMemebersFormatMessage {
            get {
                return ResourceManager.GetString("TwoMemebersFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading attachments...
        /// </summary>
        public static string UploadingAttachmentsLabel {
            get {
                return ResourceManager.GetString("UploadingAttachmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading photo....
        /// </summary>
        public static string UploadingPhoto {
            get {
                return ResourceManager.GetString("UploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured during photo uploading. Upload stopped..
        /// </summary>
        public static string UploadPhotoError {
            get {
                return ResourceManager.GetString("UploadPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not registred yet. You can send an invitation..
        /// </summary>
        public static string UserNotRegistredDescription {
            get {
                return ResourceManager.GetString("UserNotRegistredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        public static string Vibrate {
            get {
                return ResourceManager.GetString("Vibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoContentLabel {
            get {
                return ResourceManager.GetString("VideoContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was last seen {0} ago.
        /// </summary>
        public static string WasOnlineFormatMessage {
            get {
                return ResourceManager.GetString("WasOnlineFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text....
        /// </summary>
        public static string WatermarkedTextBox_DefaultWatermarkText {
            get {
                return ResourceManager.GetString("WatermarkedTextBox_DefaultWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template part is of incorrect type..
        /// </summary>
        public static string WatermarkedTextBox_TemplatePartIsOfIncorrectType {
            get {
                return ResourceManager.GetString("WatermarkedTextBox_TemplatePartIsOfIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message.
        /// </summary>
        public static string WriteMessageHint {
            get {
                return ResourceManager.GetString("WriteMessageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least 6 symbols length and equal to confirmed password..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string YourPasswordLabel {
            get {
                return ResourceManager.GetString("YourPasswordLabel", resourceCulture);
            }
        }
    }
}
